# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/dit/dit

environment:
  # global:
  #   # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  #   # /E:ON and /V:ON options are not enabled in the batch script intepreter
  #   # See: http://stackoverflow.com/a/13751649/163740
  #   CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
      CYTHON: 0
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
      CYTHON: 1
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      CYTHON: 0
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      CYTHON: 1
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
      CYTHON: 0
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
      CYTHON: 1

matrix:
  fast_finish: true
  allow_failures:
    - CYTHON: 1

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install scipy
  - ps: if ($env:CYTHON -eq '1') { conda install cython }
  - ps: if ($env:CYTHON -eq '1') { python setup.py build }
  - pip install .
  - pip install --upgrade --ignore-installed -r requirements_testing.txt

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  # - "pushd %TEMP%"
  - ps: if ($env:CYTHON -eq '1')
          { pytest }
        else
          { pytest -m "not cython" }
