name: dit_env

dependencies:
  - python >=3.9
  - colorama
  - matplotlib
  - numpy >=1.22
  - scipy >=1.7
  - sphinx >=4.0
  - pip:
    - boltons
    - debtcollector
    - hypothesis
    - ipython
    - lattices >=0.3.5
    - loguru
    - nbconvert
    - networkx >=2.6
    - PLTable
    - python-ternary
    - sphinxcontrib-bibtex
