name: dit

dependencies:
  - colorama
  - contextlib2
  - matplotlib
  - numpy >= 1.6
  - scipy >= 0.15
  - six >= 1.4
  - pip:
    - boltons
    - debtcollector
    - hypothesis
    - ipython[nbconvert]
    - python-ternary
    - sarge
    - .
